#!/usr/bin/env bash
#Bash script that

# Define signal handlers
term_handler() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 0
}

int_handler() {
    echo "Y U no love me?!"
}

quit_handler() {
    echo "Deleting PID file and terminating"
    rm /var/run/myscript.pid
    exit 0
}

# Register signal handlers
trap term_handler SIGTERM
trap int_handler SIGINT
trap quit_handler SIGQUIT

# Create PID file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done

