#!/bin/bash
#Bash for manage my process

PIDFILE=/var/run/my_process.pid
SCRIPT=/path/to/manage_my_process

start() {
    if [ -f $PIDFILE ]; then
        echo "manage_my_process is already running"
    else
        $SCRIPT &
        echo $! > $PIDFILE
        echo "manage_my_process started"
    fi
}

stop() {
    if [ ! -f $PIDFILE ]; then
        echo "manage_my_process is not running"
    else
        kill $(cat $PIDFILE)
        rm $PIDFILE
        echo "manage_my_process stopped"
    fi
}

restart() {
    stop
    start
}

case $1 in
    start) start;;
    stop) stop;;
    restart) restart;;
    *) echo "Usage: $0 {start|stop|restart}"; exit 1;;
esac

