#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name

# shellcheck disable=SC2009

# Find PIDs of processes with "bash" in their name
PIDS=$(pgrep bash)

# Loop through each PID and display the process name and PID
for PID in $PIDS; do
  NAME=$(ps -p "$PID" -o comm=)
  echo "$PID $NAME"
done

