#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.

filename=/etc/passwd

while IFS=: read -r user passwd uid gid gecos home shell;
do
  echo "$user:$uid:$home"
done < "$filename"

