#!/usr/bin/env bash
# configure ubuntu server

# Add entries to the /etc/hosts file
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Restart the networking service
service networking restart
